TAB_ENV={
	DEBUG_MODE =true,
	WX_USER="oR2LbwALAA43VxqMtW0dI1H71AqM",
	MAIN_TASK_SWITCH= false,
	EMAIL_SWITCH = true,
	WELFARE_SWITCH = true,
	LUA_VERSION="XXT", --TOUCH
	SCRIPT_VERSION = "1.0.0",
--选区
	STUDIO_PARA_DAQU= 25,

--画面静止检测的时间间隔--单位秒
	STANDING_SECONDS= 5
}